name: Main Build
on: [push]

jobs: 
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
        with:
          fetch-depth: 0
      
      - uses: actions/setup-dotnet@v5
        name: Setup .NET
        with:
          global-json-file: global.json
      
      - name: Restore Tools
        run: dotnet tool restore
        
      - name: Restore Packages
        run: dotnet restore

      - name: Install/Trust SSL Certificates
        run: |
          sudo apt update
          sudo apt-get install --reinstall ca-certificates
          
          # Create a directory for the certificate
          sudo mkdir -p /usr/local/share/ca-certificates/aspnet
          
          # Generate the certificate and export it to the directory in PEM format
          sudo dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM --no-password --verbose
          
          # Update the system's trusted CA certificates store
          sudo update-ca-certificates
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --no-restore