name: Main Build
on: [push]

jobs: 
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
        with:
          fetch-depth: 0

      - name: Update ca-certificates
        run: |
          sudo apt update
          sudo apt-get install --reinstall ca-certificates
          
      - uses: actions/setup-dotnet@v5
        name: Setup .NET
        with:
          global-json-file: global.json

      - name: Trust Dev Certs
        run: |
          sudo apt-get install --reinstall openssl libssl-dev
          
          TRUSTED_CERTS_DIRECTORY="/usr/local/share/ca-certificates"
          DEV_CERT_DIRECTORY="${TRUSTED_CERTS_DIRECTORY}/aspnet"
          # Create a directory for the certificate
          sudo mkdir -p "${DEV_CERT_DIRECTORY}"
          
          # Generate the certificate and export it to the directory in PEM format
          sudo dotnet dev-certs https -ep "${DEV_CERT_DIRECTORY}/https.crt" --format PEM --no-password --verbose
          sudo cp "${DEV_CERT_DIRECTORY}/https.crt" "${TRUSTED_CERTS_DIRECTORY}"
          # Update the system's trusted CA certificates store
          sudo update-ca-certificates

      - name: Restore Tools
        run: dotnet tool restore

      - name: Restore Packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --no-restore